### ISSUE TITLE
Feature Request: Add option to disable re-scanning directory when volumes are mounted/unmounted

### ISSUE THREAD

**Issue by jwasilko** [gobbledegook/creevey#14]
It seems that when volumes are unmounted/mounted (in my case by Time Machine), it causes Phoenix Slides to re-scan the directory that’s open (even if that directory is un-affected by the unmount/remount). This causes the app to lose it’s place in the scroll of photos, which can be really annoying when going thru a lot of photos.

Would it be possible to add a checkbox to disable this rescan behavior?

Thanks!

**Comment by gobbledegook** [comment]
No need for a checkbox this is just a straight up bug! Let me see if I can fix this.

**Comment by gobbledegook** [comment]
This should be fixed as of 1.4.8
