### ISSUE TITLE
Access to /Volumes is lost if another user is logged in.

### ISSUE THREAD

**Issue by transcriptomics** [gobbledegook/creevey#15]
If there are multiple users and more than one are logged in, then Phoenix Slides stops working entirely as it loses access to any and every directory. 

Logging out all other uses and then restarting Phoenix Slides fixes the issue. However, this also causes rescanning the image directory from scratch thereby defeating the purpose of fast user switching on a mac.

I tried providing full disk access (not desirable) to Phoenix Slides in System Preferences but even then it does not help and Phoenix Slides is unusable if multiple uses are logged in.

**Comment by gobbledegook** [comment]
What version of macOS are you using? I am trying to reproduce the issue on macOS 14 and I'm able to access all mounted volumes with two users logged in.

**Comment by gobbledegook** [comment]
I am going to close this issue for now, if you are able to reproduce this please report the bug again! Thanks.
