### ISSUE TITLE
Request: Show basic data optionally in Full Screen mode

### ISSUE THREAD

**Issue by AkaXaka** [gobbledegook/creevey#18]
When showing an image in full screen mode, it would be handy to press a button & instantly see the name of the image(+folder it's in) and which number it is out of all the images in the selection (i.e. 3/10 for image 3 out of 10).

**Comment by gobbledegook** [comment]
If you hit 'i' it should show you at least some of this information. Does that work for you, or did you want some other information?

**Comment by AkaXaka** [comment]
i works, but that feature is not easily discoverable!
