### ISSUE TITLE
Bug - Can't open images in subfolders with ä ö ü in folder name since macOS 11

### ISSUE THREAD

**Issue by bambi24x** [gobbledegook/creevey#20]
First of all thank you very much for the best image viewer on Mac!

Since the upgrade from macOS 10 to 11 and to a newer version of Phoenix Slides, the app doesn't open images in subfolders with ä ö ü in the folder name if the directory reaches a certain length.
e.g. /Users/mac/files/further ideas/businesscards/products türen/01.jpg

Phoenix Slides is able to open images if there are less subfolders.
e.g. /Users/mac/files/fotos/motorräder/cafe racer/01.jpg

Would be great if the app would support directories with more than 300 characters.

Thanks!

**Comment by gobbledegook** [comment]
Hi, I'm not able to reproduce this. I'm able to navigate to a directory like this with no problem on macOS 14:

/Users/myname/Desktop/files/further ideas/businesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusinesscardsbusi/products türen/01.jpg

yes, that directory in the middle has a name with 251 characters!

Is this issue still happening for you?

**Comment by gkertai** [comment]
A possible explanation…

There was a bug in the Big Sur 11.7.5 security update (not sure if / when it was fixed), which caused file names with [NFC](https://www.unicode.org/glossary/#normalization_form_c) normalization refuse to open. This affected many of my files with accented characters on multiple different volumes.

According to [this post](https://stackoverflow.com/a/6153713) HFS+ file names (and presumably APFS too) must be in [decomposed form](https://www.unicode.org/glossary/#normalization_form_d), but apparently macOS was previously more lenient about it. 

This was causing me problems across many different applications. I ended up using `convmv` to fix the file names (available via Homebrew).

**Comment by gobbledegook** [comment]
That is so delightfully obscure! I feel bad for those affected by this bug, but practically speaking I don't see how I can fix/workaround this without a way to reproduce the issue...

**Comment by gobbledegook** [comment]
Closing since this has presumably been fixed in a later version of macOS. If people are still running into this problem I will need detailed instructions on how to reproduce this, or somehow get my hands on a configuration that has this issue.
