### ISSUE TITLE
Feature request: support for Fujifilm RAW format (.RAF)

### ISSUE THREAD

**Issue by svaccari** [gobbledegook/creevey#23]
https://libopenraw.freedesktop.org/formats/raf/#:~:text=RAF%20is%20the%20RAW%20file,data%20and%20the%20raw%20data.

Thanks!

**Comment by gobbledegook** [comment]
macOS should already support .raf files... what version of macOS are you running?

**Comment by svaccari** [comment]
Latest Sonoma 14.1.1 (23B81).
RAF are not supported in Preview.

**Comment by gobbledegook** [comment]
i have some .raf files from my fujifilm camera and they show up in both Preview and Phoenix Slides... Do you have an example file that isn't working?

**Comment by svaccari** [comment]
Can't upload it here.
Here is the link to it: https://www.swisstransfer.com/d/820c035f-8425-46ea-9182-343c25921858

**Comment by DJFriar** [comment]
Interesting... I'm using macOS 14.1.2 and the .RAF files from my X-T5, X-T2, and X100F all load fine in Phoenix Slides.

However, I downloading your example file from your X-S10, and while quicklook does show an image (though it is distorted), Preview and Phoenix Slides both fail to open it.

I can open it fine in DxO PhotoLab. I'm not as familiar with the X-S10, but I know with my X-T5 I had some issues at first as I tried to use something other than Uncompressed RAW. Out of curiosity, do you know if the .RAF file you provided is Uncompressed RAW or one of the other options? If it isn't uncompressed, can you try one of those and see if it works?

(NOTE: I am not associated with the developer at all, I just saw the issue and shoot Fuji myself so I was confused and thought I'd try to help.)

**Comment by svaccari** [comment]
It's a compressed RAF, I'll try other option.
Thanks!

Il ven 1 dic 2023, 20:10 Tommy Craft ***@***.***> ha scritto:

**Comment by svaccari** [comment]
Yep, that is an issue with "Compressed RAW" which I accidentally selected in menu (fixed now!).
I can see uncompressed/lossless RAF files: 
<img width="423" alt="image" src="https://github.com/gobbledegook/creevey/assets/7923589/ebcc87cd-6de1-4264-93fd-5f86d76dd746">

Thanks everyone!

**Comment by kantefier** [comment]
Hey, I have the same problems with Compressed RAW files from my Fuji X-T5: I can see the previews, but the files won't open. They can't be open by Preview either, though.
OSX version is Sonoma 14.3.1

Is there a solution other than not having Compressed files in the first place?
Thank you!

**Comment by burgerga** [comment]
A sort of workaround: disable RAF format in the settings, I'm happy to browse JPEGs :)
