### ISSUE TITLE
No EXIF data shown for HEIC files

### ISSUE THREAD

**Issue by WolfgangFranke** [gobbledegook/creevey#24]
No EXIF data is shown for HEIC fotos after pressing 'I' and 'SHIFT-I'.
(But it works nice for jpg files.)

- Phoenix Slides 1.4.7 and 1.4.8 (I just realized it now, as I handle HEIC fotos first time),
- OS: MacOS 13.x and 14.x,
- my HEIC fotos are saved from iMessage (I do not have other HEIC fotos to test at the moment),
- when I open these HEIC fotos in Photoshop and save them as jpg, all original EXIF data is shown then in Phoenix Slides,

**Comment by DJFriar** [comment]
Note that images sent via iMessage has some EXIF data stripped out automatically, and some can be controlled by the sender. Just in case you are missing some data but not all data.

**Comment by WolfgangFranke** [comment]
I did some tests, all EXIF data is in the HEIC photo:
- the "Exiftool" shows all EXIF data of the HEIC photo,
- "Phoenix Slides" does not show any EXIF data of the HEIC photo,
- after conversation to to JPG, "Phoenix Slides" shows the EXIF data of the JPG, which was a HEIC before.

**Comment by gobbledegook** [comment]
It's surprisingly difficult to find the official specification for HEIF files online (apparently the ISO has made these files private/paywalled for some bizarre reason), but I've figured it out and am working on adding this!

**Comment by gobbledegook** [comment]
fixed in 672529221d34e98cc2bb5503db061ee73f632bac

heic is done to specification; raw was copy-and-paste code from dcraw and pray that it works haha
