### ISSUE TITLE
Thumbnail View does not refresh photos with new "Modify Date/Time" anymore on v1.4.8

### ISSUE THREAD

**Issue by WolfgangFranke** [gobbledegook/creevey#25]
In "Thumbnail View", a click on the folder does not update anymore the Thumbnails of changed photos, even they have a newer "Modify Date/Time". It only acts on added or deleted files when refreshing the Thumbnail View.

Scenario: After editing a photo in e.g. Photoshop, the file gets a new "Modify Date/Time", but the "Thumbnail View" will still show the old photo. I did not find a way to force the reload of a folder to detect the changed files, so I have to stop and restart Phoenix Slides to get the current photos shown in the "Thumbnail View".

- It worked in Phoenix Slides 1.4.7 , but stopped working in version 1.4.8 
- MacOS 13 and 14

**Comment by gobbledegook** [comment]
Oops, I didn't realize people were relying on that behavior! In any case version 1.5 should fix this, and then some.

**Comment by WolfgangFranke** [comment]
I confirm it works great again in 1.5, thanks.
