### ISSUE TITLE
Request: Sort by date captured/taken

### ISSUE THREAD

**Issue by DJFriar** [gobbledegook/creevey#27]
I would really, really, really love the ability to sort a folder by the date captured/taken as recorded in the EXIF data.

**Comment by gobbledegook** [comment]
Try this version:

https://blyt.net/phxslides/phxslides-150d1.dmg

I believe the behavior is correct, but the sorting is noticeably slow, since it has to load up the exif data in every file...

**Comment by gobbledegook** [comment]
added in 461c88fdf714f05b2403a64627206f925d540c2a

and it should be pretty performant too

(not supported: exif tags in plain old tiff, png, and webp)

**Comment by DJFriar** [comment]
This is awesome!!! Thank you so much!
