### ISSUE TITLE
Wrong Picture Rotation in v1.5.1 for EXIF orientation flags

### ISSUE THREAD

**Issue by WolfgangFranke** [gobbledegook/creevey#28]
In v1.5.1, the Image Orientation is wrong in both, thumbnail and full-screen mode,
for the following Picture Rotation Exif flags:
- "Right-Hand, Top"
- "Bottom, Right-Hand"
- "Left-Hand, Bottom"

It works correct for:
- "Top, Left-Hand"

I'm not sure if the Menu entry "automatic rotation" works, as it does not change any behavior.

**Comment by gobbledegook** [comment]
Yes, this is embarrassing. It will be fixed soon, I promise!

**Comment by gobbledegook** [comment]
fixed in a30d294e56dfb0f41d9d842f31e1811c68ec3715

**Comment by WolfgangFranke** [comment]
Verified it works in 1.5.2, thank you!
