### ISSUE TITLE
Hidden volume prevents files from being opened

### ISSUE THREAD

**Issue by mlei** [gobbledegook/creevey#3]
If I mount a hidden volume in 10.9.4, it does not show up in Phoenix Slides, nor will any file on the volume open in Phoenix Slides. Any attempt to open an image on a hidden volume opens the Phoenix Slides app, emits a beep and then nothing else happens.

mahler:~ mlei$ GetFileInfo /Volumes/users-schubert/
directory: "/Volumes/users-schubert"
attributes: aVbstclinmedz
created: 03/10/2009 07:02:34
modified: 04/17/2014 08:12:39

mahler:~ mlei$ mount
/dev/disk0s2 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
//mlei@schubert._smb._tcp.local/users-schubert on /Volumes/users-schubert (smbfs, nodev, nosuid, mounted by mlei)

![screen shot 2014-07-24 at 6 36 07 pm](https://cloud.githubusercontent.com/assets/764354/3697031/317884aa-139c-11e4-99bb-600ed4ac66ff.png)

EDIT: originally, I thought SMB was the issue, but it turns out that if the file is hidden, you won't be able to open anything under it.

**Comment by gobbledegook** [comment]
Got it! The "show invisibles" function was neglecting to reload the list of volumes. Fixed in 3b85e54

**Comment by gobbledegook** [comment]
As of v1.4.1 you should be able to browse files in hidden volumes/directories by dragging the file into Phoenix Slides. Please close if this is a satisfactory solution. Thanks!
