### ISSUE TITLE
Pressing ESC during viewing returns to the initial picture

### ISSUE THREAD

**Issue by corporateshark** [gobbledegook/creevey#30]
Pressing the `Esc` key during viewing returns to the initial picture in the file browser. Previous versions had this correct and put the cursor on the last viewed image in the file browser.

**Comment by gobbledegook** [comment]
Sorry about that! Please use this version until the next update officially comes out:

http://blyt.net/phxslides/phoenix-slides-153d1.dmg

**Comment by gobbledegook** [comment]
fixed in 3bd7218fdc098c06c638fa90beed72caed9300af
