### ISSUE TITLE
Regression: Application switches desktops when activating slideshow 

### ISSUE THREAD

**Issue by sacundim** [gobbledegook/creevey#31]
I observed this started in v1.5.3, and I still see it on v1.5.4. The steps I use to reproduce:

1. Have multiple Spaces (or desktops, or whatever Apple calls it now) created. I'll refer to two of them as desktop A and desktop B
2. Start Phoenix Slides from desktop A
3. Create an additional Phoenix Slides image browser window
4. Navigate to some image folders on both image browser windows
5. Move one of the image browser windows to desktop B
6. Enter slideshow on the desktop A image browser window
7. Exit slideshow
8. Switch to desktop B and its image browser window
9. Enter slideshow on the desktop B image browser window. You should observe here the horizontal desktop change animation
10. Exit that slideshow. You should observe here that you're back in desktop A, but your two image browser windows should be still one on A and the other on B.

Expected behavior, observed in older versions (I think 1.5.2):

1. No animation on step 9
2. You're still on desktop B when you exit the slideshow on step 10

Environment: MacOS Sonoma 14.1.1, ARM64

**Comment by gobbledegook** [comment]
Got it. Someone asked for the window to show up in Mission Control (formerly Expose), and I guess that changes the Spaces behavior. I added NSWindowCollectionBehaviorMoveToActiveSpace so it should stay in the same space now, try this version:

https://blyt.net/phxslides/phoenix-slides-154d1.dmg

**Comment by sacundim** [comment]
I've just confirmed that patched version eliminates the issue.

**Comment by gobbledegook** [comment]
fixed in v1.5.5

**Comment by sacundim** [comment]
I've just confirmed v1.5.5 doesn't have the issue
