### ISSUE TITLE
Regression: pressing Cmd+Del on an image does not remove it from the viewer

### ISSUE THREAD

**Issue by corporateshark** [gobbledegook/creevey#32]
Pressing `Cmd`+`Del` on an image deletes the file but does not remove it from the viewer until the folder is rescanned.

**Comment by gobbledegook** [comment]
I believe this is happening in the slideshow if the files are sorted by date.

**Comment by corporateshark** [comment]
Right, my files are sorted by date.

**Comment by gobbledegook** [comment]
Please let me know if this version fixes the issue:

https://blyt.net/phxslides/phoenix-slides-154d2.dmg

**Comment by corporateshark** [comment]
> Please let me know if this version fixes the issue:
> 
> https://blyt.net/phxslides/phoenix-slides-154d2.dmg

Just what the doctor ordered!

**Comment by gobbledegook** [comment]
fixed in v1.5.5
