### ISSUE TITLE
Picture display quality is not as good as on Preview or Xee on JPEG

### ISSUE THREAD

**Issue by therealmarv** [gobbledegook/creevey#33]
I'm currently evaluating a replacement for Xee3 (very unhappy they stopped development long time ago).

It seems Phoenix Slides checks the most important check boxes for me (like e.g. color accuracy and nice native zoom behaviour).

However I'm really picky with my image viewer of choice and have done a 1:1 comparison of Phoenix Slides, Preview and Xee with mostly JPEGs.

### The problem

I noticed that Phoenix Slides pictures are a **more blurry / less sharp** than from Preview and Xee. I've created a 200% Nearest neighbour Zoom for comparison reasons. Note: The quality difference is also visible on smaller than screen images (so the issue is not the downsampling). I'm guessing a faster decompression algorithm of JPEGs is used to make Phoenix snappier.

Is it possible to get a high quality decrompression of JPEGs (even optional in settings would be good) with Phoenix to make it equal to display quality of Preview?

The original image from this issue is available for free here: https://negativespace.co/woman-model-street/

*Look especially at the eyes, eyelashes, eyebrows, skin pores in the comparison*

#### Phoenix Sildes (more blurry)
![phoenix](https://github.com/gobbledegook/creevey/assets/1050582/ff1a3410-fb45-43b8-aa72-82c9331607b2)

#### Preview (sharper)
![preview](https://github.com/gobbledegook/creevey/assets/1050582/3121d00b-571e-4e36-bb41-3c8664dbf456)

#### 1:1 comparison on the eye region

![1to1_comparison](https://github.com/gobbledegook/creevey/assets/1050582/407fbd92-ce78-4227-a2f8-275945d5762a)

**Comment by gobbledegook** [comment]
OK I *think* I know what's going on here, but let me ask a couple questions. First, what are the steps you're taking for the Phoenix Slides comparison image? Is it (1) open the image in a slideshow, then (2) take a screenshot?

Now try this: (1) open the slideshow, (2) hit the '=' key to show the image at actual size, (3) hit the '*' key to go back to the default zoom level. When you do the comparison now, how does it look?

I think what's going on is that in regular slideshow usage, Phoenix Slides scales down images that are larger than the screen (using Image I/O's "thumbnail" API's, which I'm guessing you are correct that it does some sort of fast decompression). You can force Phoenix Slides to override this by zooming the image to a non-default scale factor. Once this happens, the app will continue to use this full size image at all scale factors.

If my guess is correct and zooming in and back out fixes the issue, it would be easy enough to add an option to always load the full size image for slideshows. It would be a tradeoff of speed and memory usage for better quality images. (I may even consider making this the default.)

**Comment by therealmarv** [comment]
Thanks for your comment. I think the issue is more complicated because there are two cases now 😅

FYI: I'm not doing the slide show function. I'm just opening the file directly in viewer mode.

### Technical information about my setup beforehand

I use a 4K monitor (native resolution 3840x2160) in 2560x1440 HiDPI mode. When I do fullscreen screenshots (using Skitch) they are 5120x2880 pixels in dimension.

### Case 1: image much larger than screen resolution

If you download (button) the [original image](https://negativespace.co/woman-model-street/) it's 8256x5504 pixels.

I've followed your instructions:

> Now try this: (1) open the slideshow, (2) hit the '=' key to show the image at actual size, (3) hit the '*' key to go back to the default zoom level. When you do the comparison now, how does it look?

**The result:** It fixes the problem! 🥳 The image looks **practically** the same now in Phoenix, Preview and Xee3 (extremely minor difference but not visible to the human eye) and with perfect sharpness.

### Case 2: image smaller than my screen resolution

I've created a new cropped image with resolution 1800x1012. I will upload it here on github (should not be resized and original):

![original](https://github.com/gobbledegook/creevey/assets/1050582/1af08c8e-fd85-435c-a822-cd38a98b3a90)

I've opened the image directly in Phoenix, Preview and Xee3 with actual size settings (no zoom in) and this is the result zoomed in into the eye region:

![small_1to1_comparison](https://github.com/gobbledegook/creevey/assets/1050582/34d1df64-ec95-47ed-94ea-dd941cb46a0a)

As you can see the problem with sharpness is still there but maybe not as pronounced as before.

### My comments/thoughts

I don't know if this valuable (ignore it if not helpful):

Either something is wrong with the resolution handling

OR

I've worked with JPEG software decompressors myself, they can be adjusted to various decompression levels. The dequantization can be stopped beforehand (which makes the decompressor faster) and then you get a less sharp decompressed JPEG back. Maybe it's not set to highest decompression level in your software (have not checked the code). Downside is a more blurry image (unfortunately a dealbreaker for me). Even commercial products using this trick like ACDsee for Mac (I would never use that program for that reason) ;)

**Comment by gobbledegook** [comment]
So the second case may be related to the fact that Phoenix Slides was not taking advantage off all the pixels on your HiDPI screen. I think I've fixed both problems, if you want to try this version:

https://blyt.net/phxslides/phoenix-slides-155d1.dmg

Zooming in on the image (using '+' or '=' or a pinch gesture on the trackpad) will always load the full image, but for now in normal (non-zoomed) usage it will still scale down images that have significantly more pixels than your screen (but the quality of the downsampling should be much better). Please try this and let me know if it gives acceptable results!

**Comment by therealmarv** [comment]
Wow & thanks 👏👏👏
This new version is remarkable. I gave it a deeper test run and I think it's the ideal balance of quality and speed! It solved both test cases with a pleasing high quality image now!

Some more details

### Case 1, larger than screen image

* Xee3: Took long time to load the 21MB JPEG (nothing visible till it fully loaded). On my system 14 seconds. Good quality at the end.
* Preview: Loaded a low quality (blurry) version and then takes a tremendous amount of time in the background to load the high quality version. It replaces the low quality version tile by tile. Total amount of loading time is longer than Xee3's 14 seconds! However quality it wise it beats Phoenix Slides and Xee3 a little bit. You can see it in the photo grain in the white parts of the eyes if you look very closely. However the speed tradeoff of this approach is too much in my opinion. The balance of speed vs. quality is not good and you are stuck with a blurry image for a long time.
* Phoenix Slides: The fastest, it took only 1-3 seconds and quality is not distinguishable to Xee3 by my eye.

![Large comparison](https://github.com/gobbledegook/creevey/assets/1050582/7fc087bb-25bc-426d-90ed-caad81271e50)

Quality wise I think all 3 look the same to my eye on the 4K monitor. The little bit more quality on the Preview App is a big nit picky and not worth the super long loading time.

### Case 2, smaller than screen image

To make it short: I think they look the same to me with my eyes on the 4K monitor. However when I take screenshots it's 5K resolution and then there is a slight difference between the 3 programs. But this difference practically disappears on my screen native resolution with my eyes looking at it.
On the screenshot: Xee3 looks the most smoothened out and Preview the most sharpest. But Phoenix Slides has the perfect middle spot. Well done

![Small comparison](https://github.com/gobbledegook/creevey/assets/1050582/d4fd7748-7788-461b-99a0-2a08f9661128)

I think you should release a new version with this fix! A big leap in JPEG display quality on HiDPI screens! And on a personal note: With this improvements I can finally replace my old friend Xee3 with Phoenix Slides after all those years! 🥹

**Comment by gobbledegook** [comment]
released with v1.5.6
