### ISSUE TITLE
Program crashes entirely when folder includes a DNG file

### ISSUE THREAD

**Issue by therealmarv** [gobbledegook/creevey#34]
### How to reproduce the bug

Version 1.5.5

Have a mixed folder with some JPEGs and one or more DNG in the folder.

DNG is a RAW file generated e.g. by Adobe Photoshop RAW or Adobe Lightroom.

Open a JPEG file.

Note: [Here](https://drive.google.com/file/d/1eo5aj-aZB7QTDbMj3XILQo68aYslUZQ8/view?usp=sharing) is a sample DNG from me to reproduce the error. You can download the DNG from the top right there.

### What happens

Phoenix Slides crashes entirely during analysing the folder. I only tried to open a JPEG and did not try to open the DNG directly. When I remove all DNG from the folder it does not crash anymore.

### What is expected

I don't expect Phoenix Slides to open RAW files like DNG really (I have other programs for that like Lightroom etc) but at the same time I don't expect it to crash entirely. A placeholder info image which says e.g. that the DNG could not be opened would be nice.

It would be great if it "only" crashes internally and gracefully on trying to access the DNG file but not taking the whole program with it.

**Comment by gobbledegook** [comment]
This looks like an unfortunate bug in dcraw (which Phoenix Slides uses to extract thumbnails). I'll try to release a fix soon, meanwhile as an extreme workaround you can disable DNG as one of the filetypes in the preferences.

**Comment by gobbledegook** [comment]
fixed in 36ec99e
