### ISSUE TITLE
size of thumbnails too small for some JPG (since v1.5.4)

### ISSUE THREAD

**Issue by WolfgangFranke** [gobbledegook/creevey#37]
In thumbnails view, the thumbnails size of some JPG are not scaling up to the usual size anymore. Since v1.5.4. , some JPGs thumbnails are shown significantly smaller than for other JPGs. The more I crop this odd kind of photo, the smaller the thumbnail gets shown. See attached Screenshots.
This issue was introduced in v1.5.4, the v1.5.3 works fine. 

The photo JPGs I tested in the screenshot below are from a Scanner with 5.000x3.000 Pixel.
But most other photo JPGs work well (e.g. from iPhone) and show the same full thumbnail size in 1.5.3 and 1.5.4.

**Comment by WolfgangFranke** [comment]
![Compare v153 - v154](https://github.com/gobbledegook/creevey/assets/49641989/52a5673b-111a-4782-b240-0b7c980c8d76)

**Comment by WolfgangFranke** [comment]
![Bildschirmfoto 2024-02-06 um 22 00 22](https://github.com/gobbledegook/creevey/assets/49641989/a7cadac0-ef5a-4c47-bda5-2cdc7b49d30b)

**Comment by WolfgangFranke** [comment]
![Bildschirmfoto 2024-02-06 um 22 02 12](https://github.com/gobbledegook/creevey/assets/49641989/d1daace2-7f6b-4d20-b6c2-a76cb0fd7fa2)

**Comment by gobbledegook** [comment]
What is your setting for Maximum Thumbnail Size in your preferences?

**Comment by WolfgangFranke** [comment]
Thanks Dominic, that was the root issue.
Setting the preferences "Maximum Thumbnail Size" to 512 did help. 
I'm not sure if versions from 1.5.4 ignore the 1.5.3 preference "Maximum Thumbnail Size" and set it to 160, or why it worked before.
Thanks, I close this issue.

**Comment by WolfgangFranke** [comment]
Setting the preference from 512 to 160 brings the problem back, but from 512 to 320 no problem occurs.
The behavior is different:
- from 512/320 to 160, it needs an App-restart to take effect,
- from 160 to 512/320 the auto-refresh of the thumbnail view helps to take effect.

I hope that helps you to decide of you need to reopen the issue.

**Comment by gobbledegook** [comment]
Could you attach one of the "wrong" images? Either your scanner is generating tiny thumbnails or Phoenix Slides is interpreting the data wrong.

**Comment by WolfgangFranke** [comment]
Hi Dominic, I sent a "wrong" scanned image by e-mail to you, the file size is >10MB and too big to upload here.

**Comment by gobbledegook** [comment]
Looks like your scanner is creating jpegs with bizarrely sized embedded thumbnails (101x67). I've made a patch to check for this circumstance of create a new thumbnail in such cases:

https://blyt.net/phxslides/phoenix-slides-156d1.dmg

**Comment by gobbledegook** [comment]
To explain more: when you set the thumbnail size preference to 160 pixels, Phoenix Slides tries to optimize by using the embedded thumbnail in jpegs, which is *supposed* to be 160x120. If you set that preference to 320/512, thumbnails are always generated from jpegs (instead of extracted from the file when present). I made the change so it also generates thumbnails if it finds an embedded thumbnail that's too small.

**Comment by WolfgangFranke** [comment]
I confirm phoenix-slides-156d1 works as expected also with the odd photos when thumbnail size preference is 160 pixels.
Thank you for describing how the 160 pixels versus 320/512 pixels setting works, this explains it nicely.
