### ISSUE TITLE
Feature Request: Enforce Dark Mode in settings

### ISSUE THREAD

**Issue by therealmarv** [gobbledegook/creevey#38]
This is only a nice to have and no bug.

I use my Mac mainly in "light" mode. But I like "dark" mode for certain apps.

Many apps allow to enforce "dark" mode in settings and especially my photo related apps (Photoshop etc.) are all on the darker side.

### Feature request

- Add an option in settings to let Phoenix Slides running it in dark mode always.
- (Optional) Make the option a choice between: light mode (enforced), dark mode (enforced), system settings

**Comment by therealmarv** [comment]
If this is helpful. I've set the target to macOS 10.14 and enforced dark mode successfully on my local build with `NSAppearance`:

https://github.com/therealmarv/creevey/blob/c377ad1b02b7c96225006de79d17439dc35468c5/CreeveyController.m#L690-L693

P.S.: I'm not a macOS programmer and do not know how to do an options dialog (yet)

**Comment by gobbledegook** [comment]
Please test this version:

https://blyt.net/phxslides/phoenix-slides-156d3.dmg

**Comment by therealmarv** [comment]
Tested it with all settings and playing with macOS theme settings and it works as intended!

However there is one new bug I've discovered on testing all scenarios. I made a new bug entry [here](https://github.com/gobbledegook/creevey/issues/40) for it.

**Comment by gobbledegook** [comment]
added in 1.5.7
