### ISSUE TITLE
HEIC files displayed in wrong Picture Rotation (JPG still ok)

### ISSUE THREAD

**Issue by WolfgangFranke** [gobbledegook/creevey#39]
In v1.5.2 the EXIF orientation flags were used correctly to show JPG and HEIC files (fix #28).
After I jumped to v1.5.6, the Image Orientation for HEIC files is now:
- wrong in full-screen mode for HEIC (JPGs it is still correct),
- correct in thumbnail mode,

**Comment by gobbledegook** [comment]
Good catch! Please test this version:

https://blyt.net/phxslides/phoenix-slides-156d3.dmg

**Comment by WolfgangFranke** [comment]
v156d3 rotates HEIC as expected, thanks for fixing that quickly.
