### ISSUE TITLE
option to start without slideshow (even though autoadvance is on)

### ISSUE THREAD

**Issue by solsang** [gobbledegook/creevey#4]
Severely need an option to avoid start slideshow at startup, even though autoadvance is on!

When doubleclicking a jpg to start phoenix slides, it goes into slideshow at once, moving away from the photo i want to see, very confusing and sometimes embarrassing (especially if i present a photo which happen to be in the downloads folder... often have had to excuse and navigate back to the right photo)

As i often use autoadvancing slideshows, this setting is remembered upon closing phoenix, and next time i open a photo i will get the same autoadvancing at once, i have set jpg default to phoenix and always want to study selected photos by doubleclicking, it is amazingly fast and useful for this

There is a nice green button to start slideshow, so i see little point in having it start when the program launches, however to keep other users workflow it would be safest to add an option in the slideshow preferences whether to have the slideshow start at program launch (default toggled on)

**Comment by gobbledegook** [comment]
I assume this is when Phoenix Slides is set to be the default application for certain image types...

@Frechmatz What would you prefer to happen when you open a file from the Finder? Just select the thumbnail in the browser window?

@solsang Are you saying that when you start a slideshow by clicking the "Start Slideshow" button you always want to have auto-advance on, but when you open a file from the Finder you always want it to open in slideshow mode with auto-advance off? As a workaround could you leave the auto-advance preference off and only start auto-advance using the keyboard (hitting '5' will do auto-advance every 5 seconds, for example, but the setting won't be remembered the next time you launch the app).

**Comment by solsang** [comment]
Yes, i would like it as you describe, when opening from a selected file finder, i get the fullscreen without slideshow, as i need to examine that exact file, often to enlarge or show others.

When i hit the slideshow button i expect the auto-advance to be on, just like in other programs (eg picasa), i have found myself clicking the slideshow and nothing happens many times

One possibility is to add a checkbox next to the slideshow botton with autoadvance on/off, it can be called "auto" to save space, and it would be easy to change depending on situation, then there will be all possibilities by having the autoadvance when start in the preferences, and the checkbox for the button!!

It is really nice to be able to change the speed with the numbers while inside the slideshow, (though i am used to space meaning start/stop action, and arrows to advance, this is less important)

**Comment by Frechmatz** [comment]
Hi, what i would like is

- when displaying an image out of finder via Phoenix-App: Scaling as configured via settings. Slide show mode disabled. (For non-scaled display of the image i would use the default MacOs-Preview)
- when displaying an image out of Phoenix: Enter into slide show mode / scale image as configured via settings.
- in image display mode of Phoenix: Allow starting/stopping slide show and going forward/backward via context menu (or by overlay controls put on top of the image, when moving the mouse to some 'hot area' of the image). The context menu should also provide to select the image within finder.

**Comment by gobbledegook** [comment]
options for slideshow and suppressing auto-advance have been added to v1.5.3
