### ISSUE TITLE
Request: Set the default way to open pictures as window mode

### ISSUE THREAD

**Issue by hazeyi** [gobbledegook/creevey#42]
Whenever I open a picture to browse, it always maximizes to fill the entire screen. I would rather browse in window mode. Please provide this option! Thank you so much

In addition, please provide cmd key plus mouse wheel zoom image shortcuts, very much needed, thank you

**Comment by hazeyi** [comment]
补充：在phoenix-slides内建图片列表浏览器打开图片时希望可以在窗口内打开
![Uploading iShot_2024-02-22_16.22.02.png…]()

**Comment by gobbledegook** [comment]
You can choose "Begin Slideshow in Window" from the Slideshow Menu, or hold down the option key when starting a slideshow. Did you want a preference to swap this behavior?

**Comment by gobbledegook** [comment]
added in https://github.com/gobbledegook/creevey/releases/tag/v1.5.9

I don't know what you mean by "cmd key plus mouse wheel zoom image shortcuts". cmd-+ and cmd-- should already work to zoom (as do + and - by themselves). Mouse wheel is currently used to scroll. Pinching on a trackpad will work to zoom.

Please feel free to open separate issue(s) for other changes!
