### ISSUE TITLE
Enhancement Request: Use "Slideshow Window" for image info

### ISSUE THREAD

**Issue by mscuthbert** [gobbledegook/creevey#45]
Thanks for adding view in Window in #12  (and for considering the #42 enhancement).

Another enhancement that would be helpful is to use the window title bar (currently always "Slideshow Window") to display either the current file name, or all the information of the File info from the bottom info bar.

Here's how another system displays images in window view:
<img width="655" alt="Screenshot 2024-02-28 at 11 10 01" src="https://github.com/gobbledegook/creevey/assets/3521479/b6c9e3c7-c9d2-42e6-95c8-ca35f129b589">

Thank you!

**Comment by gobbledegook** [comment]
added in v1.5.8
