### ISSUE TITLE
bug/feature request - slideshow stops advancing after using left arrow

### ISSUE THREAD

**Issue by hps976** [gobbledegook/creevey#48]
A slideshow stops advancing automatically when it is interrupted by using the left arrow key to go back one or more images. It will advance one image at a time using the right arrow key, but does not resume continuous playback. This behavior occurs whether or not the slideshow has been paused using the spacebar. It also occurs whether or not the slideshow is set to random or sequential playback. It would be great if the slideshow were to resume where it left off after it the back arrow shortcut was used. 

Phoenix Slides version 1.5.7 (30)
Macos 12.7.3

**Comment by gobbledegook** [comment]
So let's say you have auto-advance to 5s. Would you want to hit left arrow, then 5s later have it auto-advance to the next slide? Or would you want left arrow to pause, and require you to hit space to resume the auto-advance?

**Comment by hps976** [comment]
Hi Dominic,

Thanks for looking into this. I would prefer to resume by hitting the space bar.

XXOO Pete


H. Peter Spielmann

Professor of Molecular and Cellular Biochemistry

University of Kentucky

B445 BBSRB

741 S. Limestone Ave,

Lexington KY 40536

tel: 859-257-4790

***@***.***

________________________________

**Comment by gobbledegook** [comment]
added in https://github.com/gobbledegook/creevey/releases/tag/v1.5.9
