### ISSUE TITLE
Support of Clipboard

### ISSUE THREAD

**Issue by Frechmatz** [gobbledegook/creevey#5]
I would like support of the MacOS-Clipboard.

**Comment by gobbledegook** [comment]
Do you mean for copying files?

**Comment by Frechmatz** [comment]
Yes. Moving or copying image files into other folders within the Phoenix-Application. Or for pasting images into a mail.

**Comment by gobbledegook** [comment]
This may have to wait until there is proper support for detecting files being moved in the background. Meanwhile the workaround would be to use cmd-R to show the files in the Finder and do all your operations there...

**Comment by Frechmatz** [comment]
Thank you. I've tested with Finder and Mail and it's working fine 👍
