### ISSUE TITLE
Request: Custom full screen mode that uses the notch area of macbooks

### ISSUE THREAD

**Issue by Brog33** [gobbledegook/creevey#52]
It would be cool if the fullscreen mode could (optionally) also include the scanlines used for the app menu+camera notch on macbooks.

**Comment by gobbledegook** [comment]
I'm not sure what you mean, do you actually want the image to fill the entire screen with the notch obscuring part of the image? (and if so, why?)

**Comment by Brog33** [comment]
Exactly. The reason is simply that I like to utilize the full visible area of the screen.

**Comment by gobbledegook** [comment]
added in https://github.com/gobbledegook/creevey/releases/tag/v1.5.9
