### ISSUE TITLE
bug report: since 1.5.7 problem with sony arw files

### ISSUE THREAD

**Issue by zamomien** [gobbledegook/creevey#53]
Hi!
With version 1.5.6 it is possible to see thumbnails and open dia-show with sony *.arw files. 
In version 1.5.7 thumbnail views are displayed but starting dia-show will end in an icon that shows a broken file with width 0px and height 0px.  
What can I do to get the slideshow running again?
Thanks!

**Comment by gobbledegook** [comment]
This will be fixed in the next release! In the meantime are you OK with continuing to run on 1.5.6?

**Comment by zamomien** [comment]
> This will be fixed in the next release! In the meantime are you OK with continuing to run on 1.5.6?

No problem! Many thanks for your answer!

**Comment by gobbledegook** [comment]
fixed in https://github.com/gobbledegook/creevey/releases/tag/v1.5.9
