### ISSUE TITLE
Cannot open network shares

### ISSUE THREAD

**Issue by mindhaq** [gobbledegook/creevey#6]
The open dialog does not display any network shares. Only locally attached drives can be selected.

**Comment by gobbledegook** [comment]
Is this still an issue in the latest version? If so, what is the mount point of your network volumes? The root of the file browser is indeed limited to /Volumes. However it should be possible to load images from other volumes by dragging them into the browser window.

**Comment by gobbledegook** [comment]
😆 actually there never was an open dialog, it's just the first column of the directory browser that shows everything under /Volumes

**Comment by gobbledegook** [comment]
I'm going to close this as "configuration changed". If you want/need volumes with mount points other than /Volumes to show up in the first column you can open a new issue. Thanks!
