### ISSUE TITLE
Request: optionally show n/m in the right bottom

### ISSUE THREAD

**Issue by zetzet** [gobbledegook/creevey#61]
As an option, show in the right bottom of the slideshow window or in full screen mode that this is n out of m pictures in this directory.

**Comment by gobbledegook** [comment]
You can already see n/m at the bottom left if you hit 'i' to cycle through the info display modes. Did you mean you want to change the location of the info bar?

**Comment by zetzet** [comment]
I was blind, exactly what i wanted :-)
