### ISSUE TITLE
Request: Allow for even larger preview sizes

### ISSUE THREAD

**Issue by Julian** [gobbledegook/creevey#62]
Hi there! Thanks for writing this, it looks exactly like what I'm after.

I see there's a slider which controls how large of an image preview to show, but even at the largest setting it doesn't produce previews which are particularly large on my display. I'm obviously not expecting anything like a full-size preview, but with the largest size it isn't quite large enough to even easily be able to see whether I want to edit a photo or not.

For reference, what I see (on macOS, on a display with 2160x3840 resolution) is:

![Screenshot 2024-08-11 at 14 13 40](https://github.com/user-attachments/assets/ae222ced-0856-4076-8228-0785b40ef76c)

I *assume* this may have to do with high DPI displays but could be totally off as I don't have a lower one to check on, so perhaps this is simply as big as it gets anywhere?

If it's technically feasible though, even ~33% more wiggle room on the slider would make it possible to occasionally glance at a few more elements in the photos.

Regardless, thanks again for making the app!

**Comment by gobbledegook** [comment]
Have you already fiddled with the "Maximum Thumbnail Width" setting in the Preferences? It can go up to 512.

**Comment by Julian** [comment]
I missed that setting! Thanks, that's perfect, sorry for the noise!
