### ISSUE TITLE
Request: make looping icon optional

### ISSUE THREAD

**Issue by raafirivero** [gobbledegook/creevey#65]
Phoenix Slides is one of my favorite apps and I use it every day. The loop icon that plays when I iterate through a folder is only useful in certain situations and I'd love the option to turn it off. Usually, I open the icon in Photoshop and make it blank so it never shows. Would love to have this be optional so I can turn it on for large folders and keep it off otherwise. Thanks for your hard work on this app.

**Comment by gobbledegook** [comment]
Yes, as of v1.5.5 you can do

    defaults write net.blyt.phoenixslides SlideshowSuppressLoopIndicator -bool YES

**Comment by raafirivero** [comment]
Amazing - thanks!
