### ISSUE TITLE
Issue when I scroll through the images

### ISSUE THREAD

**Issue by MGuerrera** [gobbledegook/creevey#67]
Device: MacBook Pro M3
Operating System: macOs Sonoma
Phoenix Slides Version: 1.5.9 (32)

Description:
The app crashes when I scroll through the images with the mouse.

How to reproduce the issue:
1. Open Phoenix Slides.
2. Choose a folder.
3. Double click on a picture.
4. Cycle through the images by repeatedly clicking on the presentation window with the mouse.
5. The presentation window disappears suddenly after a few images, without showing any error messages.

Observations:
- The issue does not occur when using the arrow keys, the spacebar, or the mouse wheel.
- It seems that the issue depends on the speed at which you keep clicking, as if it recognizes a double click that causes the window to close.

**Comment by gobbledegook** [comment]
Yes, double click ends the slideshow. As I recall this was originally requested as a feature!

**Comment by MGuerrera** [comment]
I suspected it, but wasn’t sure.

I think the feature conflicts a bit with the ability to cycle through clicks, since I have to set the double-click speed to maximum in the settings to avoid accidentally closing the window.

I’m not sure how this could be solved, maybe by adding an option to enable or disable the feature.

It would also be useful to have the option to hold the click to automatically advance until the mouse button is released.

Anyway, I consider the issue resolved, thanks for your work, it’s a great app, probably the best I’ve tried so far for image viewing on macOs.

**Comment by MGuerrera** [comment]
I suspected it, but wasn’t sure.

I think the feature conflicts a bit with the ability to cycle through clicks, since I have to set the double-click speed to maximum in the settings to avoid accidentally closing the window.

I’m not sure how this could be solved, maybe by adding an option to enable or disable the feature.

It would also be useful to have the option to hold the click to automatically advance until the mouse button is released.

Anyway, I consider the issue resolved, thanks for your work, it’s a great app, probably the best I’ve tried so far for image viewing on macOs.
