### ISSUE TITLE
Suggest Changing Interpolation Type

### ISSUE THREAD

**Issue by halfSpinDoctor** [gobbledegook/creevey#8]
I have noticed poor image quality, such as jagged edges and blurry text, for slides where the resolution of the images is significantly higher than that of my display. This is for an image that is resampled (down-sampled), i.e. when the option "Show Large Images at Actual Size" is not selected.

My suggestion is to change NSImageInterpolationLow to NSImageInterpolationHigh:

https://github.com/gobbledegook/creevey/blob/95de950176bcfc4676773a14df0aacfd8a0977f8/DYImageView.m#L118

On modern hardware, using better image resampling should have minimal performance impact. I have recompiled the software on my computer and verified that this significantly improves image quality with no impact on the time it takes to flip slides (macOS 10.12 Hackintosh, Intel i5-6500, 16 GB RAM),

Thank you for considering this issues!
Best,
Sam

**Comment by gobbledegook** [comment]
You are right! Fixed in the latest version. Thank you for the suggestion!
